/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Dec 18 01:38:12 2017. */

#include "commands.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t StatusResponse_fields[5] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, StatusResponse, relayOne, relayOne, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, StatusResponse, relayTwo, relayOne, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, StatusResponse, relayThree, relayTwo, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, StatusResponse, relayFour, relayThree, 0),
    PB_LAST_FIELD
};

const pb_field_t OffRequest_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, OffRequest, relay, relay, 0),
    PB_LAST_FIELD
};

const pb_field_t OnRequest_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, OnRequest, relay, relay, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
