/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Dec 18 03:49:36 2017. */

#include "commands.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const Relay CommandRequest_relay_default = Relay_ALL;
const int32_t CommandRequest_iterations_default = 1;
const int32_t CommandRequest_onMillis_default = 500;
const int32_t CommandRequest_offMillis_default = 500;
const int32_t CommandRequest_pauseMillis_default = 0;


const pb_field_t StatusResponse_fields[5] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, StatusResponse, relayOne, relayOne, &StatusResponse_Status_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, StatusResponse, relayTwo, relayOne, &StatusResponse_Status_fields),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, StatusResponse, relayThree, relayTwo, &StatusResponse_Status_fields),
    PB_FIELD(  4, MESSAGE , REQUIRED, STATIC  , OTHER, StatusResponse, relayFour, relayThree, &StatusResponse_Status_fields),
    PB_LAST_FIELD
};

const pb_field_t StatusResponse_Status_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, StatusResponse_Status, relay, relay, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, StatusResponse_Status, state, relay, 0),
    PB_LAST_FIELD
};

const pb_field_t CommandRequest_fields[7] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, CommandRequest, command, command, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, CommandRequest, relay, command, &CommandRequest_relay_default),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, CommandRequest, iterations, relay, &CommandRequest_iterations_default),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, CommandRequest, onMillis, iterations, &CommandRequest_onMillis_default),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, CommandRequest, offMillis, onMillis, &CommandRequest_offMillis_default),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, CommandRequest, pauseMillis, offMillis, &CommandRequest_pauseMillis_default),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(StatusResponse, relayOne) < 65536 && pb_membersize(StatusResponse, relayTwo) < 65536 && pb_membersize(StatusResponse, relayThree) < 65536 && pb_membersize(StatusResponse, relayFour) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_StatusResponse_StatusResponse_Status_CommandRequest)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(StatusResponse, relayOne) < 256 && pb_membersize(StatusResponse, relayTwo) < 256 && pb_membersize(StatusResponse, relayThree) < 256 && pb_membersize(StatusResponse, relayFour) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_StatusResponse_StatusResponse_Status_CommandRequest)
#endif


/* @@protoc_insertion_point(eof) */
