/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Dec 18 02:19:42 2017. */

#include "commands.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const Relay CommandRequest_relay_default = Relay_ALL;
const int32_t CommandRequest_iterations_default = 1;
const int32_t CommandRequest_onMillis_default = 500;
const int32_t CommandRequest_offMillis_default = 500;
const int32_t CommandRequest_pauseMillis_default = 0;


const pb_field_t StatusResponse_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, StatusResponse, status, status, &StatusResponse_Status_fields),
    PB_LAST_FIELD
};

const pb_field_t StatusResponse_Status_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, StatusResponse_Status, relay, relay, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, StatusResponse_Status, state, relay, 0),
    PB_LAST_FIELD
};

const pb_field_t CommandRequest_fields[7] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, CommandRequest, command, command, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, CommandRequest, relay, command, &CommandRequest_relay_default),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, CommandRequest, iterations, relay, &CommandRequest_iterations_default),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, CommandRequest, onMillis, iterations, &CommandRequest_onMillis_default),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, CommandRequest, offMillis, onMillis, &CommandRequest_offMillis_default),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, CommandRequest, pauseMillis, offMillis, &CommandRequest_pauseMillis_default),
    PB_LAST_FIELD
};





/* @@protoc_insertion_point(eof) */
