/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.2-dev at Sun Dec 17 23:43:54 2017. */

#ifndef _PB_COMMANDS_PB_H_
#define _PB_COMMANDS_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _OffRequest {
    pb_callback_t relay;
} OffRequest;

typedef struct _OnRequest {
    pb_callback_t relay;
} OnRequest;

typedef struct _StatusResponse {
    bool relayOne;
    bool relayTwo;
    bool relayThree;
    bool relayFour;
} StatusResponse;

/* Default values for struct fields */

/* Struct field encoding specification for nanopb */
extern const pb_field_t StatusResponse_fields[5];
extern const pb_field_t OffRequest_fields[2];
extern const pb_field_t OnRequest_fields[2];

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
