/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.2-dev at Sun Dec 17 23:43:54 2017. */

#include "commands.pb.h"



const pb_field_t StatusResponse_fields[5] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC, StatusResponse, relayOne, relayOne, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC, StatusResponse, relayTwo, relayOne, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC, StatusResponse, relayThree, relayTwo, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC, StatusResponse, relayFour, relayThree, 0),
    PB_LAST_FIELD
};

const pb_field_t OffRequest_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, OffRequest, relay, relay, 0),
    PB_LAST_FIELD
};

const pb_field_t OnRequest_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, OnRequest, relay, relay, 0),
    PB_LAST_FIELD
};


